---
apiVersion: v1
kind: Namespace
metadata:
  name: sriov-passthrough-cni
  labels:
    name: sriovpassthrough
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sriov-passthrough-cni
  namespace: sriov-passthrough-cni
  labels:
    tier: node
    name: sriovpassthrough
    app: sriovpassthrough
spec:
  selector:
    matchLabels:
      name: sriovpassthrough
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        name: sriovpassthrough
        app: sriovpassthrough
    spec:
      hostNetwork: true
      nodeSelector:
        hardwareSupport: sriov-nic
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-sriov-passthrough-cni
        command: ["install-plugin"]
        args: ["/host/opt/cni/bin"]
        image: 'quay.io/kubevirtci/sriov-passthrough-cni:v1.2'
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
      - name: cnibin
        hostPath:
          path: /var/lib/cni/bin
          type: Directory
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-passthrough-cni
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "type": "sriov-passthrough-cni"
    }
