---
driver:
  name: docker

platforms:
  - name: instance
    image: quay.io/bcarey/prow-deploy:v20230907-1aadcc
    privileged: True
    etc_hosts:
      "gcsweb.prowdeploy.ci": "127.0.0.1"
      "deck.prowdeploy.ci": "127.0.0.1"
      "hook.prowdeploy.ci": "127.0.0.1"
    volumes:
      - /tmp/prow-deploy-molecule:/docker-graph

provisioner:
  name: ansible

scenario:
  test_sequence:
    - create
    - prepare
    - converge
    - verify
