---
- name: copy production kustomize files
  copy:
    src: '{{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/{{ item }}'
    dest: '{{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}'
  delegate_to: '{{ inventory_hostname }}'
  loop:
    - kustomization.yaml
    - patches
    - resources

- name: prepare production resources for testing usage
  block:
    - name: patch ghproxy pvc class
      shell: |
        yq w -i {{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/patches/StrategicMerge/ghproxy.yaml spec.storageClassName local
    - name: patch greenhouse and docker-mirror-proxy pvc size
      shell: |
        yq w -i {{ project_infra_root }}/github/ci/prow-deploy/kustom/components/greenhouse/pv/resources/pvc.yaml spec.resources.requests.storage 10Gi
        yq w -i {{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/resources/docker-mirror-proxy_pvc.yaml spec.resources.requests.storage 10Gi
    - name: patch ingresses
      shell: |
        yq m -ix {{ project_infra_root }}/github/ci/prow-deploy/kustom/base/manifests/local/{{ item }}-ingress.yaml {{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/patches/StrategicMerge/{{ item }}-ingress.yaml
        yq d -i {{ project_infra_root }}/github/ci/prow-deploy/kustom/base/manifests/local/{{ item }}-ingress.yaml spec.tls[0].secretName
      loop:
        - deck
        - gcsweb
    - name: remove resource patching
      shell: |
        yq d -i {{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/patches/JsonRFC6902/{{ item }}.yaml '(path==/spec/template/spec/containers/0/resources)'
      loop:
        - deck_deployment
        - prow_controller_manager_deployment
    - name: create hmac secret
      shell: |
        kubectl create secret -n kubevirt-prow generic hmac-token --from-file=hmac={{ project_infra_root }}/github/ci/prow-deploy/kustom/overlays/{{ deploy_environment }}/resources/hmac.yaml
      changed_when: false
      environment:
        KUBECONFIG: '{{ kubeconfig_path }}'

    - name: Create kubeconfig secret
      copy:
        src: '{{ kubeconfig_path }}'
        dest: '{{ secrets_dir }}/kubeconfig'
        remote_src: true

    - name: Create kubeconfig-build-test-infra-trusted secret
      copy:
        src: '{{ kubeconfig_path }}'
        dest: '{{ secrets_dir }}/kubeconfig-build-test-infra-trusted'
        remote_src: true

    - name: Create kubeconfig-build-k8s-prow-builds
      copy:
        src: '{{ kubeconfig_path }}'
        dest: '{{ secrets_dir }}/kubeconfig-build-k8s-prow-builds'
        remote_src: true

    - name: Create kubeconfig-build-rules-k8s
      copy:
        src: '{{ kubeconfig_path }}'
        dest: '{{ secrets_dir }}/kubeconfig-build-rules-k8s'
        remote_src: true
