---
gitHubToken: "/etc/github/oauth"
includedConfigPaths:
  - "/config/github/ci/prow-deploy/kustom/base/configs/current/config"
  - "/config/github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources"
  - "/config/github/ci/prow-deploy/kustom/base/manifests/local"
  - "/config/github/ci/prow-deploy/kustom/base/manifests/test_infra"
excludedConfigPaths: []
extraFiles:
  - "/config/hack/bump-prow.sh"
targetVersion: upstream
upstreamURLBase: "https://raw.githubusercontent.com/kubernetes/test-infra/master"
prefixes:
  - name: "Prow"
    prefix: "us-docker.pkg.dev/k8s-infra-prow/images"
    refConfigFile: "config/prow/cluster/deck_deployment.yaml"
    repo: "https://github.com/kubernetes/test-infra"
    summarise: true
    consistentImages: true
    consistentImageExceptions:
      - "us-docker.pkg.dev/k8s-infra-prow/images/alpine"
      - "us-docker.pkg.dev/k8s-infra-prow/images/analyze"
      - "us-docker.pkg.dev/k8s-infra-prow/images/commenter"
      - "us-docker.pkg.dev/k8s-infra-prow/images/configurator"
      - "us-docker.pkg.dev/k8s-infra-prow/images/gcsweb"
      - "us-docker.pkg.dev/k8s-infra-prow/images/gencred"
      - "us-docker.pkg.dev/k8s-infra-prow/images/git"
      - "us-docker.pkg.dev/k8s-infra-prow/images/issue-creator"
      - "us-docker.pkg.dev/k8s-infra-prow/images/label_sync"
      - "us-docker.pkg.dev/k8s-infra-prow/images/pr-creator"
