# Requires kustomize v3
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../components/docker-mirror-proxy/base
  - ../../components/greenhouse/base
  - resources/docker-mirror-proxy_pvc.yaml
  # templated resources

components:
  - ../../components/docker-mirror-proxy/pv
  - ../../components/greenhouse/pv

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: docker-mirror
    path: patches/StrategicMerge/docker-mirror_deployment.yaml

  - target:
      version: v1
      kind: PersistentVolumeClaim
      namespace: default
      name: .*
    path: patches/JsonRFC6902/prow-namespace.yaml


generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: oauth-token
    files:
      - oauth=secrets/oauth-token
    type: Opaque
  - name: oauth-token
    namespace: kubevirt-prow-jobs
    files:
      - oauth=secrets/oauth-token
    type: Opaque
  - name: gcs
    files:
      - secrets/service-account.json
    type: Opaque
  - name: gcs
    namespace: kubevirt-prow-jobs
    files:
      - secrets/service-account.json
    type: Opaque
  - name: slack-token
    files:
      - token=secrets/slack-token
    type: Opaque
  - name: cookie
    files:
      - secret=secrets/cookie
    type: Opaque
  - name: github-oauth-config
    files:
      - secret=secrets/github-oauth-config
    type: Opaque
  - name: kubeconfig
    files:
      - config=secrets/kubeconfig
    type: Opaque
  - name: kubeconfig-build-test-infra-trusted
    files:
      - kubeconfig=secrets/kubeconfig-build-test-infra-trusted
  - name: kubeconfig-build-k8s-prow-builds
    files:
      - kubeconfig=secrets/kubeconfig-build-k8s-prow-builds
  - name: kubeconfig-build-rules-k8s
    files:
      - kubeconfig=secrets/kubeconfig-build-rules-k8s
  - name: unsplash-api-key
    literals:
      - honk.txt=
  - name: kubevirtci-docker-credential
    namespace: kubevirt-prow-jobs
    # username=dockerUser
    # password=dockerPass
    envs:
    - secrets/kubevirtci-docker-credential
    type: Opaque

  - name: kubevirtci-quay-credential
    namespace: kubevirt-prow-jobs
    # username=quayUser
    # password=quayPass
    envs:
    - secrets/kubevirtci-quay-credential
    type: Opaque
  - name: kubevirtci-installer-pull-token
    namespace: kubevirt-prow-jobs
    files:
      # installerPullToken
      - token=secrets/kubevirtci-installer-pull-token
    type: Opaque
  - name: commenter-oauth-token
    namespace: kubevirt-prow-jobs
    # githubCommenterToken
    files:
      - oauth=secrets/commenter-oauth-token
    type: Opaque
  - name: kubevirtci-coveralls-token
    namespace: kubevirt-prow-jobs
    files:
      # coverallsToken
      - token=secrets/kubevirtci-coveralls-token
    type: Opaque
  - name: kubevirtci-fossa-token
    namespace: kubevirt-prow-jobs
    files:
      # fossaToken
      - token=secrets/kubevirtci-fossa-token
    type: Opaque
  - name: prow-kubevirtbot-github-ssh-secret
    namespace: kubevirt-prow-jobs
    files:
      # prowKubevirtbotSSHPrivateKey
      - token=secrets/prow-kubevirtbot-github-ssh-secret
    type: Opaque
